export PATH="$HOME/recipe3/scripts:$PATH"

alias src="source $HOME/recipe3/envSetup.sh"
alias rFi="cd $HOME/recipe3/ingredients/rFiles"
alias ing="cd $HOME/recipe3/ingredients"
alias rec="cd $HOME/recipe3/recipes"
alias home="cd $HOME/recipe3"
alias inge="vim $HOME/recipe3/ingredients/ingredients.r"
alias upd="cat $HOME/recipe3/ingredients/ingredients.r | parseR > $HOME/recipe3/ingredients/Ingredients.py"
alias tupd="cat $HOME/recipe3/ingredients/ingredients.r | parseR"
