export PATH="$HOME/recipe3/scripts:$PATH"

alias rFi="cd $HOME/recipe3/ingredients/rFiles"
alias ing="cd $HOME/recipe3/ingredients"
alias rec="cd $HOME/recipe3/recipes"
alias home="cd $HOME/recipe3"
alias spi="vim $HOME/recipe3/ingredients/rFiles/spices.r"
alias veg="vim $HOME/recipe3/ingredients/rFiles/vegtables.r"
alias upding1="cat $HOME/recipe3/ingredients/rFiles/spices.r | parseR > $HOME/recipe3/ingredients/Spices.py"
alias upding2="cat $HOME/recipe3/ingredients/rFiles/vegtables.r | parseR > $HOME/recipe3/ingredients/Vegtables.py"
alias upd="upding1; upding2"
